# fly.toml app configuration file generated for adoratrices on 2023-10-16T19:59:09-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "adoratrices"
primary_region = "mia"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
